# Generated by Django 2.2 on 2020-11-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Ingredients_in_recipe', to='recipes.Ingredient'),
        ),
    ]
