# Generated by Django 3.1.3 on 2020-11-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.IntegerField(choices=[(1, 'завтрак'), (2, 'обед'), (3, 'ужин')], null=True),
        ),
    ]
