# Generated by Django 3.1.3 on 2020-11-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201122_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.CharField(choices=[('BR', 'завтрак'), ('LN', 'обед'), ('DN', 'ужин')], max_length=2, null=True),
        ),
    ]
