# Generated by Django 3.1.3 on 2020-11-22 06:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20201122_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'завтрак'), (2, 'обед'), (3, 'ужин')], max_length=5, null=True),
        ),
    ]
