# Generated by Django 3.1.3 on 2020-11-23 02:21

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20201122_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'завтрак'), (2, 'обед'), (3, 'ужин')], max_length=5, null=True),
        ),
    ]
