# Generated by Django 3.1.3 on 2020-11-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20201123_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients_in_recipe',
            new_name='IngredientsInRecipe',
        ),
    ]
