# Generated by Django 3.1.3 on 2020-11-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20201123_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsinrecipe',
            options={'verbose_name': 'Ингредиенты в рецептах'},
        ),
    ]
